site_name: Social Media & Web Analytics @ TiSEM, 2022

nav:
  - Home: 
    - Welcome: home/index.md
    - Announcements: home/announcements.md
    - Course Objectives: home/course_objectives.md
    - Meet the Instructors: home/instructors.md
  - Course Preparation:
    - Installation Guide: course_prep/software_install.md
    - Coding Bootcamp: course_prep/course_prep.md
  - Class Material:
    - Week 1: classes/week_01.md
    - Week 2: classes/week_02.md
    - Week 3: classes/week_03.md
    - Week 4: classes/week_04.md
    - Week 5: classes/week_05.md
    - Week 6: classes/week_06.md
    - Week 7: classes/week_07.md
  - Assessment: 
    - Final Project: final_project.md
    - Group Assignments: group_assignment.md
  - Code of Conduct:
    - Social Rules: social_rules.md
    - Code of Conduct: conduct.md
  - Misc.:
    - License: license.md
    - Citation: citation.md
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tisem-digital-marketing
    - icon: fontawesome/brands/slack
      link: https://tisem-smwa.slack.com