site_name: Social Media & Web Analytics @ TiSEM, 2022

nav:
  - Home: 
    - Welcome: home/index.md
    - Announcements: home/announcements.md
    - Course Objectives: home/course_objectives.md
    - Meet the Instructors: home/instructors.md
  - Course Preparation:
    - Installation Guide: software_install.md
    - Coding Bootcamp: course_prep.md
  - Classes:
    - Week 1 - Social Media: week_01.md
    - Week 2 - Online Reputation: week_02.md
    - Week 3 - Casuality: week_03.md
    - Week 4 - Word of Mouth: week_04.md
    - Week 5 - Influencers: week_05.md
    - Week 6 - Viral Marketing: week_06.md
    - Week 7 - Social Advertising: week_07.md
  - Assessment: 
    - Final Project: final_project.md
    - Group Assignments: group_assignment.md
  - Code of Conduct:
    - Social Rules: social_rules.md
    - Code of Conduct: conduct.md
  - Misc.:
    - License: license.md
    - Citation: citation.md
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tisem-digital-marketing
    - icon: fontawesome/brands/slack
      link: https://tisem-smwa.slack.com